server {
    listen 80;
    server_name smartera.bclabum.si;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Optional: handle static files efficiently
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf|map)$ {
        expires 1y;
        log_not_found off;
    }
}
